config-version: 0

metrics:
  enable: true

prefix:
  normal: "§f[§6服务器§f] "

  extend:
    enable: false
    prefix: ""

spawn:
  enable: true

  lock-sapwn: true
  no-damage: true
  protect: true


resource:
  enable: true

  url: "https://hub.fastgit.xyz/lRENyaaa/RYServerTexture/releases/download/v1.1/Pack.zip"
  hash: "2fa9b5326e064b24499edcf9569a3c466bd739ae"


protect:
  enable: true

  anti-user-name:
    enable: true

  not-boom:
    enable: true

    tnt: true
    ender-crystal: true
    creeper: true
    wither-skull: true
    wither: true
    fire-ball: true
    tnt-minecart: true
    wither-destroy: true
    block-explode: true
    other: false

  res-limit:
    enable: true

    worlds:
      - otd_dungeon
      - spawn

  lectern-crash-fix:
    enable: true

  reserved-users:
    enable: true

    list:
      - RENaa_FD


bedrock:
  tpa:
    enable: true

    commands:
      accept: "tpaccept"
      deny: "tpdeny"

    form:
      title: "传送菜单"
      accept: "同意传送"
      accept-icon: "textures/ui/realms_green_check.png"
      deny: "拒绝传送"
      deny-icon: "textures/ui/realms_red_x.png"

    contents:
      unknown: "未知的传送方式,来自 %s"
      tpa: "%s 想要让他传送到你这里"
      tpahere: "%s 想要让你传送到他那里"

  quickshop:
    enable: true

    forms:
      main:
        title: "商店菜单"
        content: "请输入你要购买/出售的物品数量\n物品价格: %s 金币"
        input: "§7123"

      setting:
        title: "商店设置"
        content: "商店设置"
        change-type: "切换商店状态"
        change-type-icon:  "textures/ui/arrow_dark_right_stretch.png"
        set-price: "修改商店价格"
        set-price-icon: "textures/ui/store_home_icon.png"
        delete: "§c删除商店"
        delete-icon: "textures/ui/realms_red_x.png"

      set-pirce:
        title: "商店菜单"
        content: "请输入你要修改的商店价格"
        input: "§7123"

      delete-confirm:
        title: "§l你确定?"
        content: "删除商店"
        confirm: "确定"
        confirm-icon: "textures/ui/realms_green_check.png"

  respawn:
    enable: true

    commands:
      back: "back"
      home: "home"

    form:
      title: "菜单"
      content: "你死亡了，下一步你想要"
      back: "回到死亡点"
      back-icon: "textures/ui/arrow_dark_right_stretch.png"
      home: "回家"
      home-icon: "textures/ui/store_home_icon.png"
      spawn: "留在主城"
      spawn-icon: "textures/ui/realms_red_x.png"



